// ForgeMind project-memory graph — Neo4j Cypher bulk load.
// Paste into Neo4j Browser (run as one script) or `cypher-shell < forgemind-graph.cypher`.
// Clear previous load (optional):
//   MATCH (n) WHERE n.forgemind = true DETACH DELETE n;

MERGE (:Route {id: "route:activity", label: "activity", path: "apps/api/app/api/routes/activity.py", forgemind: true});
MERGE (:Route {id: "route:agents", label: "agents", path: "apps/api/app/api/routes/agents.py", forgemind: true});
MERGE (:Route {id: "route:analytics", label: "analytics", path: "apps/api/app/api/routes/analytics.py", forgemind: true});
MERGE (:Route {id: "route:annotations", label: "annotations", path: "apps/api/app/api/routes/annotations.py", forgemind: true});
MERGE (:Route {id: "route:api_ecosystem", label: "api_ecosystem", path: "apps/api/app/api/routes/api_ecosystem.py", forgemind: true});
MERGE (:Route {id: "route:approvals", label: "approvals", path: "apps/api/app/api/routes/approvals.py", forgemind: true});
MERGE (:Route {id: "route:architecture", label: "architecture", path: "apps/api/app/api/routes/architecture.py", forgemind: true});
MERGE (:Route {id: "route:artifacts", label: "artifacts", path: "apps/api/app/api/routes/artifacts.py", forgemind: true});
MERGE (:Route {id: "route:audit", label: "audit", path: "apps/api/app/api/routes/audit.py", forgemind: true});
MERGE (:Route {id: "route:auth", label: "auth", path: "apps/api/app/api/routes/auth.py", forgemind: true});
MERGE (:Route {id: "route:chat", label: "chat", path: "apps/api/app/api/routes/chat.py", forgemind: true});
MERGE (:Route {id: "route:checkpoints", label: "checkpoints", path: "apps/api/app/api/routes/checkpoints.py", forgemind: true});
MERGE (:Route {id: "route:code_intelligence", label: "code_intelligence", path: "apps/api/app/api/routes/code_intelligence.py", forgemind: true});
MERGE (:Route {id: "route:code_ops", label: "code_ops", path: "apps/api/app/api/routes/code_ops.py", forgemind: true});
MERGE (:Route {id: "route:collaboration", label: "collaboration", path: "apps/api/app/api/routes/collaboration.py", forgemind: true});
MERGE (:Route {id: "route:comments", label: "comments", path: "apps/api/app/api/routes/comments.py", forgemind: true});
MERGE (:Route {id: "route:composition", label: "composition", path: "apps/api/app/api/routes/composition.py", forgemind: true});
MERGE (:Route {id: "route:connectors", label: "connectors", path: "apps/api/app/api/routes/connectors.py", forgemind: true});
MERGE (:Route {id: "route:constitution", label: "constitution", path: "apps/api/app/api/routes/constitution.py", forgemind: true});
MERGE (:Route {id: "route:constitution_suggestions", label: "constitution_suggestions", path: "apps/api/app/api/routes/constitution_suggestions.py", forgemind: true});
MERGE (:Route {id: "route:costs", label: "costs", path: "apps/api/app/api/routes/costs.py", forgemind: true});
MERGE (:Route {id: "route:council", label: "council", path: "apps/api/app/api/routes/council.py", forgemind: true});
MERGE (:Route {id: "route:credential_vault", label: "credential_vault", path: "apps/api/app/api/routes/credential_vault.py", forgemind: true});
MERGE (:Route {id: "route:delivery", label: "delivery", path: "apps/api/app/api/routes/delivery.py", forgemind: true});
MERGE (:Route {id: "route:enterprise_governance", label: "enterprise_governance", path: "apps/api/app/api/routes/enterprise_governance.py", forgemind: true});
MERGE (:Route {id: "route:escalation", label: "escalation", path: "apps/api/app/api/routes/escalation.py", forgemind: true});
MERGE (:Route {id: "route:events", label: "events", path: "apps/api/app/api/routes/events.py", forgemind: true});
MERGE (:Route {id: "route:github_integration", label: "github_integration", path: "apps/api/app/api/routes/github_integration.py", forgemind: true});
MERGE (:Route {id: "route:governance", label: "governance", path: "apps/api/app/api/routes/governance.py", forgemind: true});
MERGE (:Route {id: "route:health", label: "health", path: "apps/api/app/api/routes/health.py", forgemind: true});
MERGE (:Route {id: "route:knowledge", label: "knowledge", path: "apps/api/app/api/routes/knowledge.py", forgemind: true});
MERGE (:Route {id: "route:members", label: "members", path: "apps/api/app/api/routes/members.py", forgemind: true});
MERGE (:Route {id: "route:memory", label: "memory", path: "apps/api/app/api/routes/memory.py", forgemind: true});
MERGE (:Route {id: "route:metrics", label: "metrics", path: "apps/api/app/api/routes/metrics.py", forgemind: true});
MERGE (:Route {id: "route:notifications", label: "notifications", path: "apps/api/app/api/routes/notifications.py", forgemind: true});
MERGE (:Route {id: "route:phase_agent_profiles", label: "phase_agent_profiles", path: "apps/api/app/api/routes/phase_agent_profiles.py", forgemind: true});
MERGE (:Route {id: "route:planner", label: "planner", path: "apps/api/app/api/routes/planner.py", forgemind: true});
MERGE (:Route {id: "route:planner_results", label: "planner_results", path: "apps/api/app/api/routes/planner_results.py", forgemind: true});
MERGE (:Route {id: "route:project_templates", label: "project_templates", path: "apps/api/app/api/routes/project_templates.py", forgemind: true});
MERGE (:Route {id: "route:projects", label: "projects", path: "apps/api/app/api/routes/projects.py", forgemind: true});
MERGE (:Route {id: "route:release_ops", label: "release_ops", path: "apps/api/app/api/routes/release_ops.py", forgemind: true});
MERGE (:Route {id: "route:replay", label: "replay", path: "apps/api/app/api/routes/replay.py", forgemind: true});
MERGE (:Route {id: "route:repos", label: "repos", path: "apps/api/app/api/routes/repos.py", forgemind: true});
MERGE (:Route {id: "route:retry", label: "retry", path: "apps/api/app/api/routes/retry.py", forgemind: true});
MERGE (:Route {id: "route:run_lifecycle", label: "run_lifecycle", path: "apps/api/app/api/routes/run_lifecycle.py", forgemind: true});
MERGE (:Route {id: "route:runs", label: "runs", path: "apps/api/app/api/routes/runs.py", forgemind: true});
MERGE (:Route {id: "route:saved_views", label: "saved_views", path: "apps/api/app/api/routes/saved_views.py", forgemind: true});
MERGE (:Route {id: "route:search_knowledge", label: "search_knowledge", path: "apps/api/app/api/routes/search_knowledge.py", forgemind: true});
MERGE (:Route {id: "route:streaming", label: "streaming", path: "apps/api/app/api/routes/streaming.py", forgemind: true});
MERGE (:Route {id: "route:tasks", label: "tasks", path: "apps/api/app/api/routes/tasks.py", forgemind: true});
MERGE (:Route {id: "route:trust", label: "trust", path: "apps/api/app/api/routes/trust.py", forgemind: true});
MERGE (:Route {id: "route:workspaces", label: "workspaces", path: "apps/api/app/api/routes/workspaces.py", forgemind: true});
MERGE (:Service {id: "service:activity_service", label: "activity_service", path: "apps/api/app/services/activity_service.py", forgemind: true});
MERGE (:Service {id: "service:adaptive_orchestrator", label: "adaptive_orchestrator", path: "apps/api/app/services/adaptive_orchestrator.py", forgemind: true});
MERGE (:Service {id: "service:adaptive_retry_service", label: "adaptive_retry_service", path: "apps/api/app/services/adaptive_retry_service.py", forgemind: true});
MERGE (:Service {id: "service:adr_service", label: "adr_service", path: "apps/api/app/services/adr_service.py", forgemind: true});
MERGE (:Service {id: "service:agent_service", label: "agent_service", path: "apps/api/app/services/agent_service.py", forgemind: true});
MERGE (:Service {id: "service:api_key_service", label: "api_key_service", path: "apps/api/app/services/api_key_service.py", forgemind: true});
MERGE (:Service {id: "service:approval_enhanced_service", label: "approval_enhanced_service", path: "apps/api/app/services/approval_enhanced_service.py", forgemind: true});
MERGE (:Service {id: "service:approval_service", label: "approval_service", path: "apps/api/app/services/approval_service.py", forgemind: true});
MERGE (:Service {id: "service:architecture_approval_service", label: "architecture_approval_service", path: "apps/api/app/services/architecture_approval_service.py", forgemind: true});
MERGE (:Service {id: "service:architecture_rule_service", label: "architecture_rule_service", path: "apps/api/app/services/architecture_rule_service.py", forgemind: true});
MERGE (:Service {id: "service:architecture_service", label: "architecture_service", path: "apps/api/app/services/architecture_service.py", forgemind: true});
MERGE (:Service {id: "service:artifact_service", label: "artifact_service", path: "apps/api/app/services/artifact_service.py", forgemind: true});
MERGE (:Service {id: "service:artifact_version_service", label: "artifact_version_service", path: "apps/api/app/services/artifact_version_service.py", forgemind: true});
MERGE (:Service {id: "service:audit_export_service", label: "audit_export_service", path: "apps/api/app/services/audit_export_service.py", forgemind: true});
MERGE (:Service {id: "service:audit_log_service", label: "audit_log_service", path: "apps/api/app/services/audit_log_service.py", forgemind: true});
MERGE (:Service {id: "service:authz_service", label: "authz_service", path: "apps/api/app/services/authz_service.py", forgemind: true});
MERGE (:Service {id: "service:background_scheduler", label: "background_scheduler", path: "apps/api/app/services/background_scheduler.py", forgemind: true});
MERGE (:Service {id: "service:chat_service", label: "chat_service", path: "apps/api/app/services/chat_service.py", forgemind: true});
MERGE (:Service {id: "service:ci_pipeline_service", label: "ci_pipeline_service", path: "apps/api/app/services/ci_pipeline_service.py", forgemind: true});
MERGE (:Service {id: "service:code_graph_service", label: "code_graph_service", path: "apps/api/app/services/code_graph_service.py", forgemind: true});
MERGE (:Service {id: "service:code_ops_service", label: "code_ops_service", path: "apps/api/app/services/code_ops_service.py", forgemind: true});
MERGE (:Service {id: "service:code_review_service", label: "code_review_service", path: "apps/api/app/services/code_review_service.py", forgemind: true});
MERGE (:Service {id: "service:comment_service", label: "comment_service", path: "apps/api/app/services/comment_service.py", forgemind: true});
MERGE (:Service {id: "service:compliance_report_service", label: "compliance_report_service", path: "apps/api/app/services/compliance_report_service.py", forgemind: true});
MERGE (:Service {id: "service:composition_service", label: "composition_service", path: "apps/api/app/services/composition_service.py", forgemind: true});
MERGE (:Service {id: "service:connector_service", label: "connector_service", path: "apps/api/app/services/connector_service.py", forgemind: true});
MERGE (:Service {id: "service:constitution_service", label: "constitution_service", path: "apps/api/app/services/constitution_service.py", forgemind: true});
MERGE (:Service {id: "service:constitution_suggestion_service", label: "constitution_suggestion_service", path: "apps/api/app/services/constitution_suggestion_service.py", forgemind: true});
MERGE (:Service {id: "service:convention_service", label: "convention_service", path: "apps/api/app/services/convention_service.py", forgemind: true});
MERGE (:Service {id: "service:cost_tracking_service", label: "cost_tracking_service", path: "apps/api/app/services/cost_tracking_service.py", forgemind: true});
MERGE (:Service {id: "service:council_service", label: "council_service", path: "apps/api/app/services/council_service.py", forgemind: true});
MERGE (:Service {id: "service:credential_vault_service", label: "credential_vault_service", path: "apps/api/app/services/credential_vault_service.py", forgemind: true});
MERGE (:Service {id: "service:dashboard_alert_service", label: "dashboard_alert_service", path: "apps/api/app/services/dashboard_alert_service.py", forgemind: true});
MERGE (:Service {id: "service:delivery_artifact_service", label: "delivery_artifact_service", path: "apps/api/app/services/delivery_artifact_service.py", forgemind: true});
MERGE (:Service {id: "service:deployment_readiness_service", label: "deployment_readiness_service", path: "apps/api/app/services/deployment_readiness_service.py", forgemind: true});
MERGE (:Service {id: "service:design_doc_service", label: "design_doc_service", path: "apps/api/app/services/design_doc_service.py", forgemind: true});
MERGE (:Service {id: "service:diff_intelligence_service", label: "diff_intelligence_service", path: "apps/api/app/services/diff_intelligence_service.py", forgemind: true});
MERGE (:Service {id: "service:drift_detection_service", label: "drift_detection_service", path: "apps/api/app/services/drift_detection_service.py", forgemind: true});
MERGE (:Service {id: "service:email_service", label: "email_service", path: "apps/api/app/services/email_service.py", forgemind: true});
MERGE (:Service {id: "service:embedding_service", label: "embedding_service", path: "apps/api/app/services/embedding_service.py", forgemind: true});
MERGE (:Service {id: "service:encryption_service", label: "encryption_service", path: "apps/api/app/services/encryption_service.py", forgemind: true});
MERGE (:Service {id: "service:environment_service", label: "environment_service", path: "apps/api/app/services/environment_service.py", forgemind: true});
MERGE (:Service {id: "service:escalation_service", label: "escalation_service", path: "apps/api/app/services/escalation_service.py", forgemind: true});
MERGE (:Service {id: "service:event_service", label: "event_service", path: "apps/api/app/services/event_service.py", forgemind: true});
MERGE (:Service {id: "service:execution_checkpoint_service", label: "execution_checkpoint_service", path: "apps/api/app/services/execution_checkpoint_service.py", forgemind: true});
MERGE (:Service {id: "service:execution_health_service", label: "execution_health_service", path: "apps/api/app/services/execution_health_service.py", forgemind: true});
MERGE (:Service {id: "service:execution_service", label: "execution_service", path: "apps/api/app/services/execution_service.py", forgemind: true});
MERGE (:Service {id: "service:flakiness_complexity_service", label: "flakiness_complexity_service", path: "apps/api/app/services/flakiness_complexity_service.py", forgemind: true});
MERGE (:Service {id: "service:github_client", label: "github_client", path: "apps/api/app/services/github_client.py", forgemind: true});
MERGE (:Service {id: "service:github_installation_service", label: "github_installation_service", path: "apps/api/app/services/github_installation_service.py", forgemind: true});
MERGE (:Service {id: "service:github_rate_limiter", label: "github_rate_limiter", path: "apps/api/app/services/github_rate_limiter.py", forgemind: true});
MERGE (:Service {id: "service:governance_engine_service", label: "governance_engine_service", path: "apps/api/app/services/governance_engine_service.py", forgemind: true});
MERGE (:Service {id: "service:governance_service", label: "governance_service", path: "apps/api/app/services/governance_service.py", forgemind: true});
MERGE (:Service {id: "service:impact_analysis_service", label: "impact_analysis_service", path: "apps/api/app/services/impact_analysis_service.py", forgemind: true});
MERGE (:Service {id: "service:integration_service", label: "integration_service", path: "apps/api/app/services/integration_service.py", forgemind: true});
MERGE (:Service {id: "service:ip_allowlist_service", label: "ip_allowlist_service", path: "apps/api/app/services/ip_allowlist_service.py", forgemind: true});
MERGE (:Service {id: "service:issue_sync_service", label: "issue_sync_service", path: "apps/api/app/services/issue_sync_service.py", forgemind: true});
MERGE (:Service {id: "service:knowledge_service", label: "knowledge_service", path: "apps/api/app/services/knowledge_service.py", forgemind: true});
MERGE (:Service {id: "service:membership_service", label: "membership_service", path: "apps/api/app/services/membership_service.py", forgemind: true});
MERGE (:Service {id: "service:mention_service", label: "mention_service", path: "apps/api/app/services/mention_service.py", forgemind: true});
MERGE (:Service {id: "service:merge_readiness_service", label: "merge_readiness_service", path: "apps/api/app/services/merge_readiness_service.py", forgemind: true});
MERGE (:Service {id: "service:notification_delivery_service", label: "notification_delivery_service", path: "apps/api/app/services/notification_delivery_service.py", forgemind: true});
MERGE (:Service {id: "service:notification_digest_service", label: "notification_digest_service", path: "apps/api/app/services/notification_digest_service.py", forgemind: true});
MERGE (:Service {id: "service:notification_service", label: "notification_service", path: "apps/api/app/services/notification_service.py", forgemind: true});
MERGE (:Service {id: "service:operational_timeline_service", label: "operational_timeline_service", path: "apps/api/app/services/operational_timeline_service.py", forgemind: true});
MERGE (:Service {id: "service:pattern_debt_service", label: "pattern_debt_service", path: "apps/api/app/services/pattern_debt_service.py", forgemind: true});
MERGE (:Service {id: "service:phase_agent_profile_service", label: "phase_agent_profile_service", path: "apps/api/app/services/phase_agent_profile_service.py", forgemind: true});
MERGE (:Service {id: "service:plan_artifact_service", label: "plan_artifact_service", path: "apps/api/app/services/plan_artifact_service.py", forgemind: true});
MERGE (:Service {id: "service:planner_service", label: "planner_service", path: "apps/api/app/services/planner_service.py", forgemind: true});
MERGE (:Service {id: "service:post_release_service", label: "post_release_service", path: "apps/api/app/services/post_release_service.py", forgemind: true});
MERGE (:Service {id: "service:pr_service", label: "pr_service", path: "apps/api/app/services/pr_service.py", forgemind: true});
MERGE (:Service {id: "service:project_overview_service", label: "project_overview_service", path: "apps/api/app/services/project_overview_service.py", forgemind: true});
MERGE (:Service {id: "service:project_service", label: "project_service", path: "apps/api/app/services/project_service.py", forgemind: true});
MERGE (:Service {id: "service:project_template_service", label: "project_template_service", path: "apps/api/app/services/project_template_service.py", forgemind: true});
MERGE (:Service {id: "service:recommendation_service", label: "recommendation_service", path: "apps/api/app/services/recommendation_service.py", forgemind: true});
MERGE (:Service {id: "service:refactor_recommendation_service", label: "refactor_recommendation_service", path: "apps/api/app/services/refactor_recommendation_service.py", forgemind: true});
MERGE (:Service {id: "service:release_confidence_service", label: "release_confidence_service", path: "apps/api/app/services/release_confidence_service.py", forgemind: true});
MERGE (:Service {id: "service:release_gate_service", label: "release_gate_service", path: "apps/api/app/services/release_gate_service.py", forgemind: true});
MERGE (:Service {id: "service:release_package_service", label: "release_package_service", path: "apps/api/app/services/release_package_service.py", forgemind: true});
MERGE (:Service {id: "service:replay_service", label: "replay_service", path: "apps/api/app/services/replay_service.py", forgemind: true});
MERGE (:Service {id: "service:repo_service", label: "repo_service", path: "apps/api/app/services/repo_service.py", forgemind: true});
MERGE (:Service {id: "service:retention_policy_service", label: "retention_policy_service", path: "apps/api/app/services/retention_policy_service.py", forgemind: true});
MERGE (:Service {id: "service:rollback_readiness_service", label: "rollback_readiness_service", path: "apps/api/app/services/rollback_readiness_service.py", forgemind: true});
MERGE (:Service {id: "service:run_annotation_service", label: "run_annotation_service", path: "apps/api/app/services/run_annotation_service.py", forgemind: true});
MERGE (:Service {id: "service:run_comparison_service", label: "run_comparison_service", path: "apps/api/app/services/run_comparison_service.py", forgemind: true});
MERGE (:Service {id: "service:run_lifecycle_service", label: "run_lifecycle_service", path: "apps/api/app/services/run_lifecycle_service.py", forgemind: true});
MERGE (:Service {id: "service:run_memory_enrichment_service", label: "run_memory_enrichment_service", path: "apps/api/app/services/run_memory_enrichment_service.py", forgemind: true});
MERGE (:Service {id: "service:run_memory_service", label: "run_memory_service", path: "apps/api/app/services/run_memory_service.py", forgemind: true});
MERGE (:Service {id: "service:saved_view_service", label: "saved_view_service", path: "apps/api/app/services/saved_view_service.py", forgemind: true});
MERGE (:Service {id: "service:search_service", label: "search_service", path: "apps/api/app/services/search_service.py", forgemind: true});
MERGE (:Service {id: "service:slash_command_service", label: "slash_command_service", path: "apps/api/app/services/slash_command_service.py", forgemind: true});
MERGE (:Service {id: "service:spec_plan_approval_service", label: "spec_plan_approval_service", path: "apps/api/app/services/spec_plan_approval_service.py", forgemind: true});
MERGE (:Service {id: "service:spec_plan_validation_service", label: "spec_plan_validation_service", path: "apps/api/app/services/spec_plan_validation_service.py", forgemind: true});
MERGE (:Service {id: "service:spec_service", label: "spec_service", path: "apps/api/app/services/spec_service.py", forgemind: true});
MERGE (:Service {id: "service:sso_configuration_service", label: "sso_configuration_service", path: "apps/api/app/services/sso_configuration_service.py", forgemind: true});
MERGE (:Service {id: "service:stream_service", label: "stream_service", path: "apps/api/app/services/stream_service.py", forgemind: true});
MERGE (:Service {id: "service:structural_health_service", label: "structural_health_service", path: "apps/api/app/services/structural_health_service.py", forgemind: true});
MERGE (:Service {id: "service:task_assignment_service", label: "task_assignment_service", path: "apps/api/app/services/task_assignment_service.py", forgemind: true});
MERGE (:Service {id: "service:task_service", label: "task_service", path: "apps/api/app/services/task_service.py", forgemind: true});
MERGE (:Service {id: "service:template_inheritance_service", label: "template_inheritance_service", path: "apps/api/app/services/template_inheritance_service.py", forgemind: true});
MERGE (:Service {id: "service:topology_mapper_service", label: "topology_mapper_service", path: "apps/api/app/services/topology_mapper_service.py", forgemind: true});
MERGE (:Service {id: "service:traceability_service", label: "traceability_service", path: "apps/api/app/services/traceability_service.py", forgemind: true});
MERGE (:Service {id: "service:trust_scoring_service", label: "trust_scoring_service", path: "apps/api/app/services/trust_scoring_service.py", forgemind: true});
MERGE (:Service {id: "service:unified_activity_service", label: "unified_activity_service", path: "apps/api/app/services/unified_activity_service.py", forgemind: true});
MERGE (:Service {id: "service:user_activity_service", label: "user_activity_service", path: "apps/api/app/services/user_activity_service.py", forgemind: true});
MERGE (:Service {id: "service:velocity_quality_service", label: "velocity_quality_service", path: "apps/api/app/services/velocity_quality_service.py", forgemind: true});
MERGE (:Service {id: "service:webhook_connector_service", label: "webhook_connector_service", path: "apps/api/app/services/webhook_connector_service.py", forgemind: true});
MERGE (:Service {id: "service:webhook_service", label: "webhook_service", path: "apps/api/app/services/webhook_service.py", forgemind: true});
MERGE (:Service {id: "service:workspace_service", label: "workspace_service", path: "apps/api/app/services/workspace_service.py", forgemind: true});
MERGE (:Model {id: "model:activity", label: "activity", path: "apps/api/app/models/activity.py", forgemind: true});
MERGE (:Model {id: "model:agent", label: "agent", path: "apps/api/app/models/agent.py", forgemind: true});
MERGE (:Model {id: "model:analytics_metrics", label: "analytics_metrics", path: "apps/api/app/models/analytics_metrics.py", forgemind: true});
MERGE (:Model {id: "model:api_ecosystem", label: "api_ecosystem", path: "apps/api/app/models/api_ecosystem.py", forgemind: true});
MERGE (:Model {id: "model:approval_delegation", label: "approval_delegation", path: "apps/api/app/models/approval_delegation.py", forgemind: true});
MERGE (:Model {id: "model:approval_request", label: "approval_request", path: "apps/api/app/models/approval_request.py", forgemind: true});
MERGE (:Model {id: "model:architecture", label: "architecture", path: "apps/api/app/models/architecture.py", forgemind: true});
MERGE (:Model {id: "model:artifact", label: "artifact", path: "apps/api/app/models/artifact.py", forgemind: true});
MERGE (:Model {id: "model:code_intelligence", label: "code_intelligence", path: "apps/api/app/models/code_intelligence.py", forgemind: true});
MERGE (:Model {id: "model:code_ops", label: "code_ops", path: "apps/api/app/models/code_ops.py", forgemind: true});
MERGE (:Model {id: "model:comment", label: "comment", path: "apps/api/app/models/comment.py", forgemind: true});
MERGE (:Model {id: "model:connector", label: "connector", path: "apps/api/app/models/connector.py", forgemind: true});
MERGE (:Model {id: "model:constitution_suggestion", label: "constitution_suggestion", path: "apps/api/app/models/constitution_suggestion.py", forgemind: true});
MERGE (:Model {id: "model:cost_record", label: "cost_record", path: "apps/api/app/models/cost_record.py", forgemind: true});
MERGE (:Model {id: "model:council", label: "council", path: "apps/api/app/models/council.py", forgemind: true});
MERGE (:Model {id: "model:credential_vault", label: "credential_vault", path: "apps/api/app/models/credential_vault.py", forgemind: true});
MERGE (:Model {id: "model:enterprise_governance", label: "enterprise_governance", path: "apps/api/app/models/enterprise_governance.py", forgemind: true});
MERGE (:Model {id: "model:escalation", label: "escalation", path: "apps/api/app/models/escalation.py", forgemind: true});
MERGE (:Model {id: "model:execution_checkpoint", label: "execution_checkpoint", path: "apps/api/app/models/execution_checkpoint.py", forgemind: true});
MERGE (:Model {id: "model:execution_event", label: "execution_event", path: "apps/api/app/models/execution_event.py", forgemind: true});
MERGE (:Model {id: "model:github_integration", label: "github_integration", path: "apps/api/app/models/github_integration.py", forgemind: true});
MERGE (:Model {id: "model:governance_policy", label: "governance_policy", path: "apps/api/app/models/governance_policy.py", forgemind: true});
MERGE (:Model {id: "model:membership", label: "membership", path: "apps/api/app/models/membership.py", forgemind: true});
MERGE (:Model {id: "model:notification", label: "notification", path: "apps/api/app/models/notification.py", forgemind: true});
MERGE (:Model {id: "model:phase_agent_profile", label: "phase_agent_profile", path: "apps/api/app/models/phase_agent_profile.py", forgemind: true});
MERGE (:Model {id: "model:planner_result", label: "planner_result", path: "apps/api/app/models/planner_result.py", forgemind: true});
MERGE (:Model {id: "model:project", label: "project", path: "apps/api/app/models/project.py", forgemind: true});
MERGE (:Model {id: "model:project_connector_link", label: "project_connector_link", path: "apps/api/app/models/project_connector_link.py", forgemind: true});
MERGE (:Model {id: "model:project_constitution", label: "project_constitution", path: "apps/api/app/models/project_constitution.py", forgemind: true});
MERGE (:Model {id: "model:project_knowledge", label: "project_knowledge", path: "apps/api/app/models/project_knowledge.py", forgemind: true});
MERGE (:Model {id: "model:project_template", label: "project_template", path: "apps/api/app/models/project_template.py", forgemind: true});
MERGE (:Model {id: "model:release_ops", label: "release_ops", path: "apps/api/app/models/release_ops.py", forgemind: true});
MERGE (:Model {id: "model:replay_snapshot", label: "replay_snapshot", path: "apps/api/app/models/replay_snapshot.py", forgemind: true});
MERGE (:Model {id: "model:repo_connection", label: "repo_connection", path: "apps/api/app/models/repo_connection.py", forgemind: true});
MERGE (:Model {id: "model:run", label: "run", path: "apps/api/app/models/run.py", forgemind: true});
MERGE (:Model {id: "model:run_annotation", label: "run_annotation", path: "apps/api/app/models/run_annotation.py", forgemind: true});
MERGE (:Model {id: "model:saved_view", label: "saved_view", path: "apps/api/app/models/saved_view.py", forgemind: true});
MERGE (:Model {id: "model:search_knowledge", label: "search_knowledge", path: "apps/api/app/models/search_knowledge.py", forgemind: true});
MERGE (:Model {id: "model:sso_configuration", label: "sso_configuration", path: "apps/api/app/models/sso_configuration.py", forgemind: true});
MERGE (:Model {id: "model:task", label: "task", path: "apps/api/app/models/task.py", forgemind: true});
MERGE (:Model {id: "model:trust_score", label: "trust_score", path: "apps/api/app/models/trust_score.py", forgemind: true});
MERGE (:Model {id: "model:user", label: "user", path: "apps/api/app/models/user.py", forgemind: true});
MERGE (:Model {id: "model:workspace", label: "workspace", path: "apps/api/app/models/workspace.py", forgemind: true});
MERGE (:Schema {id: "schema:activity", label: "activity", path: "apps/api/app/schemas/activity.py", forgemind: true});
MERGE (:Schema {id: "schema:agent", label: "agent", path: "apps/api/app/schemas/agent.py", forgemind: true});
MERGE (:Schema {id: "schema:approval", label: "approval", path: "apps/api/app/schemas/approval.py", forgemind: true});
MERGE (:Schema {id: "schema:architecture", label: "architecture", path: "apps/api/app/schemas/architecture.py", forgemind: true});
MERGE (:Schema {id: "schema:artifact", label: "artifact", path: "apps/api/app/schemas/artifact.py", forgemind: true});
MERGE (:Schema {id: "schema:auth", label: "auth", path: "apps/api/app/schemas/auth.py", forgemind: true});
MERGE (:Schema {id: "schema:code_ops", label: "code_ops", path: "apps/api/app/schemas/code_ops.py", forgemind: true});
MERGE (:Schema {id: "schema:comment", label: "comment", path: "apps/api/app/schemas/comment.py", forgemind: true});
MERGE (:Schema {id: "schema:connector", label: "connector", path: "apps/api/app/schemas/connector.py", forgemind: true});
MERGE (:Schema {id: "schema:constitution", label: "constitution", path: "apps/api/app/schemas/constitution.py", forgemind: true});
MERGE (:Schema {id: "schema:constitution_suggestion", label: "constitution_suggestion", path: "apps/api/app/schemas/constitution_suggestion.py", forgemind: true});
MERGE (:Schema {id: "schema:cost", label: "cost", path: "apps/api/app/schemas/cost.py", forgemind: true});
MERGE (:Schema {id: "schema:council", label: "council", path: "apps/api/app/schemas/council.py", forgemind: true});
MERGE (:Schema {id: "schema:credential_vault", label: "credential_vault", path: "apps/api/app/schemas/credential_vault.py", forgemind: true});
MERGE (:Schema {id: "schema:enterprise_governance", label: "enterprise_governance", path: "apps/api/app/schemas/enterprise_governance.py", forgemind: true});
MERGE (:Schema {id: "schema:escalation", label: "escalation", path: "apps/api/app/schemas/escalation.py", forgemind: true});
MERGE (:Schema {id: "schema:execution_checkpoint", label: "execution_checkpoint", path: "apps/api/app/schemas/execution_checkpoint.py", forgemind: true});
MERGE (:Schema {id: "schema:execution_event", label: "execution_event", path: "apps/api/app/schemas/execution_event.py", forgemind: true});
MERGE (:Schema {id: "schema:github_integration", label: "github_integration", path: "apps/api/app/schemas/github_integration.py", forgemind: true});
MERGE (:Schema {id: "schema:governance", label: "governance", path: "apps/api/app/schemas/governance.py", forgemind: true});
MERGE (:Schema {id: "schema:knowledge", label: "knowledge", path: "apps/api/app/schemas/knowledge.py", forgemind: true});
MERGE (:Schema {id: "schema:membership", label: "membership", path: "apps/api/app/schemas/membership.py", forgemind: true});
MERGE (:Schema {id: "schema:notification", label: "notification", path: "apps/api/app/schemas/notification.py", forgemind: true});
MERGE (:Schema {id: "schema:phase_agent_profile", label: "phase_agent_profile", path: "apps/api/app/schemas/phase_agent_profile.py", forgemind: true});
MERGE (:Schema {id: "schema:planner_result", label: "planner_result", path: "apps/api/app/schemas/planner_result.py", forgemind: true});
MERGE (:Schema {id: "schema:project", label: "project", path: "apps/api/app/schemas/project.py", forgemind: true});
MERGE (:Schema {id: "schema:project_template", label: "project_template", path: "apps/api/app/schemas/project_template.py", forgemind: true});
MERGE (:Schema {id: "schema:prompt_intake", label: "prompt_intake", path: "apps/api/app/schemas/prompt_intake.py", forgemind: true});
MERGE (:Schema {id: "schema:release_ops", label: "release_ops", path: "apps/api/app/schemas/release_ops.py", forgemind: true});
MERGE (:Schema {id: "schema:replay", label: "replay", path: "apps/api/app/schemas/replay.py", forgemind: true});
MERGE (:Schema {id: "schema:repo", label: "repo", path: "apps/api/app/schemas/repo.py", forgemind: true});
MERGE (:Schema {id: "schema:run", label: "run", path: "apps/api/app/schemas/run.py", forgemind: true});
MERGE (:Schema {id: "schema:run_annotation", label: "run_annotation", path: "apps/api/app/schemas/run_annotation.py", forgemind: true});
MERGE (:Schema {id: "schema:saved_view", label: "saved_view", path: "apps/api/app/schemas/saved_view.py", forgemind: true});
MERGE (:Schema {id: "schema:search_knowledge", label: "search_knowledge", path: "apps/api/app/schemas/search_knowledge.py", forgemind: true});
MERGE (:Schema {id: "schema:task", label: "task", path: "apps/api/app/schemas/task.py", forgemind: true});
MERGE (:Schema {id: "schema:trust", label: "trust", path: "apps/api/app/schemas/trust.py", forgemind: true});
MERGE (:Schema {id: "schema:workspace", label: "workspace", path: "apps/api/app/schemas/workspace.py", forgemind: true});
MERGE (:LibClient {id: "lib:activity", label: "activity", path: "apps/web/lib/activity.ts", forgemind: true});
MERGE (:LibClient {id: "lib:agents", label: "agents", path: "apps/web/lib/agents.ts", forgemind: true});
MERGE (:LibClient {id: "lib:api", label: "api", path: "apps/web/lib/api.ts", forgemind: true});
MERGE (:LibClient {id: "lib:approvals", label: "approvals", path: "apps/web/lib/approvals.ts", forgemind: true});
MERGE (:LibClient {id: "lib:architecture", label: "architecture", path: "apps/web/lib/architecture.ts", forgemind: true});
MERGE (:LibClient {id: "lib:artifacts", label: "artifacts", path: "apps/web/lib/artifacts.ts", forgemind: true});
MERGE (:LibClient {id: "lib:audit", label: "audit", path: "apps/web/lib/audit.ts", forgemind: true});
MERGE (:LibClient {id: "lib:auth-context", label: "auth-context", path: "apps/web/lib/auth-context.tsx", forgemind: true});
MERGE (:LibClient {id: "lib:chat", label: "chat", path: "apps/web/lib/chat.ts", forgemind: true});
MERGE (:LibClient {id: "lib:connectors", label: "connectors", path: "apps/web/lib/connectors.ts", forgemind: true});
MERGE (:LibClient {id: "lib:constitution-suggestions", label: "constitution-suggestions", path: "apps/web/lib/constitution-suggestions.ts", forgemind: true});
MERGE (:LibClient {id: "lib:constitution", label: "constitution", path: "apps/web/lib/constitution.ts", forgemind: true});
MERGE (:LibClient {id: "lib:costs", label: "costs", path: "apps/web/lib/costs.ts", forgemind: true});
MERGE (:LibClient {id: "lib:council", label: "council", path: "apps/web/lib/council.ts", forgemind: true});
MERGE (:LibClient {id: "lib:dashboards", label: "dashboards", path: "apps/web/lib/dashboards.ts", forgemind: true});
MERGE (:LibClient {id: "lib:escalations", label: "escalations", path: "apps/web/lib/escalations.ts", forgemind: true});
MERGE (:LibClient {id: "lib:events", label: "events", path: "apps/web/lib/events.ts", forgemind: true});
MERGE (:LibClient {id: "lib:governance", label: "governance", path: "apps/web/lib/governance.ts", forgemind: true});
MERGE (:LibClient {id: "lib:knowledge", label: "knowledge", path: "apps/web/lib/knowledge.ts", forgemind: true});
MERGE (:LibClient {id: "lib:notifications", label: "notifications", path: "apps/web/lib/notifications.ts", forgemind: true});
MERGE (:LibClient {id: "lib:phase-profiles", label: "phase-profiles", path: "apps/web/lib/phase-profiles.ts", forgemind: true});
MERGE (:LibClient {id: "lib:planner", label: "planner", path: "apps/web/lib/planner.ts", forgemind: true});
MERGE (:LibClient {id: "lib:project-members", label: "project-members", path: "apps/web/lib/project-members.ts", forgemind: true});
MERGE (:LibClient {id: "lib:projects", label: "projects", path: "apps/web/lib/projects.ts", forgemind: true});
MERGE (:LibClient {id: "lib:release-ops", label: "release-ops", path: "apps/web/lib/release-ops.ts", forgemind: true});
MERGE (:LibClient {id: "lib:replay", label: "replay", path: "apps/web/lib/replay.ts", forgemind: true});
MERGE (:LibClient {id: "lib:runs", label: "runs", path: "apps/web/lib/runs.ts", forgemind: true});
MERGE (:LibClient {id: "lib:stream", label: "stream", path: "apps/web/lib/stream.ts", forgemind: true});
MERGE (:LibClient {id: "lib:tasks", label: "tasks", path: "apps/web/lib/tasks.ts", forgemind: true});
MERGE (:LibClient {id: "lib:templates", label: "templates", path: "apps/web/lib/templates.ts", forgemind: true});
MERGE (:LibClient {id: "lib:trust", label: "trust", path: "apps/web/lib/trust.ts", forgemind: true});
MERGE (:LibClient {id: "lib:vault", label: "vault", path: "apps/web/lib/vault.ts", forgemind: true});
MERGE (:LibClient {id: "lib:workspaces", label: "workspaces", path: "apps/web/lib/workspaces.ts", forgemind: true});
MERGE (:Page {id: "page:activity", label: "activity", path: "apps/web/app/dashboard/activity", forgemind: true});
MERGE (:Page {id: "page:agents", label: "agents", path: "apps/web/app/dashboard/agents", forgemind: true});
MERGE (:Page {id: "page:analytics", label: "analytics", path: "apps/web/app/dashboard/analytics", forgemind: true});
MERGE (:Page {id: "page:approvals", label: "approvals", path: "apps/web/app/dashboard/approvals", forgemind: true});
MERGE (:Page {id: "page:architecture", label: "architecture", path: "apps/web/app/dashboard/architecture", forgemind: true});
MERGE (:Page {id: "page:artifacts", label: "artifacts", path: "apps/web/app/dashboard/artifacts", forgemind: true});
MERGE (:Page {id: "page:audit", label: "audit", path: "apps/web/app/dashboard/audit", forgemind: true});
MERGE (:Page {id: "page:code-explorer", label: "code-explorer", path: "apps/web/app/dashboard/code-explorer", forgemind: true});
MERGE (:Page {id: "page:connectors", label: "connectors", path: "apps/web/app/dashboard/connectors", forgemind: true});
MERGE (:Page {id: "page:costs", label: "costs", path: "apps/web/app/dashboard/costs", forgemind: true});
MERGE (:Page {id: "page:council", label: "council", path: "apps/web/app/dashboard/council", forgemind: true});
MERGE (:Page {id: "page:escalations", label: "escalations", path: "apps/web/app/dashboard/escalations", forgemind: true});
MERGE (:Page {id: "page:governance", label: "governance", path: "apps/web/app/dashboard/governance", forgemind: true});
MERGE (:Page {id: "page:knowledge", label: "knowledge", path: "apps/web/app/dashboard/knowledge", forgemind: true});
MERGE (:Page {id: "page:notifications", label: "notifications", path: "apps/web/app/dashboard/notifications", forgemind: true});
MERGE (:Page {id: "page:projects", label: "projects", path: "apps/web/app/dashboard/projects", forgemind: true});
MERGE (:Page {id: "page:releases", label: "releases", path: "apps/web/app/dashboard/releases", forgemind: true});
MERGE (:Page {id: "page:replay", label: "replay", path: "apps/web/app/dashboard/replay", forgemind: true});
MERGE (:Page {id: "page:reviews", label: "reviews", path: "apps/web/app/dashboard/reviews", forgemind: true});
MERGE (:Page {id: "page:runs", label: "runs", path: "apps/web/app/dashboard/runs", forgemind: true});
MERGE (:Page {id: "page:sandbox", label: "sandbox", path: "apps/web/app/dashboard/sandbox", forgemind: true});
MERGE (:Page {id: "page:settings", label: "settings", path: "apps/web/app/dashboard/settings", forgemind: true});
MERGE (:Page {id: "page:trust", label: "trust", path: "apps/web/app/dashboard/trust", forgemind: true});
MERGE (:Page {id: "page:vault", label: "vault", path: "apps/web/app/dashboard/vault", forgemind: true});
MERGE (:Page {id: "page:workspaces", label: "workspaces", path: "apps/web/app/dashboard/workspaces", forgemind: true});
MERGE (:Page {id: "page:dashboard", label: "dashboard", path: "apps/web/app/dashboard", forgemind: true});

MATCH (a:Route {id: "route:activity"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:activity"}), (b:Schema {id: "schema:activity"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:agents"}), (b:Schema {id: "schema:agent"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:analytics"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:analytics"}), (b:Model {id: "model:analytics_metrics"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:annotations"}), (b:Schema {id: "schema:run_annotation"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:annotations"}), (b:Model {id: "model:run_annotation"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:api_ecosystem"}), (b:Model {id: "model:api_ecosystem"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:approvals"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:approvals"}), (b:Schema {id: "schema:approval"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:approvals"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:architecture"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:architecture"}), (b:Schema {id: "schema:architecture"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:architecture"}), (b:Schema {id: "schema:approval"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:architecture"}), (b:Model {id: "model:architecture"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:artifacts"}), (b:Schema {id: "schema:artifact"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:audit"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:audit"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:auth"}), (b:Schema {id: "schema:auth"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:auth"}), (b:Model {id: "model:user"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:checkpoints"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:checkpoints"}), (b:Schema {id: "schema:execution_checkpoint"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:checkpoints"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:code_intelligence"}), (b:Service {id: "service:planner_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:code_intelligence"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:code_intelligence"}), (b:Model {id: "model:code_intelligence"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:code_ops"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:code_ops"}), (b:Schema {id: "schema:code_ops"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:code_ops"}), (b:Model {id: "model:code_ops"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:collaboration"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:comments"}), (b:Schema {id: "schema:comment"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:comments"}), (b:Model {id: "model:comment"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:composition"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:connectors"}), (b:Schema {id: "schema:connector"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:connectors"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:connectors"}), (b:Model {id: "model:planner_result"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:connectors"}), (b:Model {id: "model:project"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:constitution"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:constitution"}), (b:Schema {id: "schema:constitution"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:constitution_suggestions"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:constitution_suggestions"}), (b:Schema {id: "schema:constitution_suggestion"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:constitution_suggestions"}), (b:Model {id: "model:constitution_suggestion"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:costs"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:costs"}), (b:Schema {id: "schema:cost"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:council"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:council"}), (b:Schema {id: "schema:council"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:council"}), (b:Model {id: "model:council"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:credential_vault"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:credential_vault"}), (b:Schema {id: "schema:credential_vault"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:credential_vault"}), (b:Model {id: "model:credential_vault"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:credential_vault"}), (b:Model {id: "model:connector"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:delivery"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:delivery"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:enterprise_governance"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:enterprise_governance"}), (b:Schema {id: "schema:enterprise_governance"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:enterprise_governance"}), (b:Model {id: "model:enterprise_governance"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:enterprise_governance"}), (b:Model {id: "model:workspace"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:escalation"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:escalation"}), (b:Schema {id: "schema:escalation"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:escalation"}), (b:Model {id: "model:escalation"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:events"}), (b:Schema {id: "schema:execution_event"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:github_integration"}), (b:Service {id: "service:github_client"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:github_integration"}), (b:Schema {id: "schema:github_integration"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:github_integration"}), (b:Model {id: "model:github_integration"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:governance"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:governance"}), (b:Schema {id: "schema:governance"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:governance"}), (b:Model {id: "model:governance_policy"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:knowledge"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:knowledge"}), (b:Schema {id: "schema:knowledge"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:knowledge"}), (b:Model {id: "model:project_knowledge"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:members"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:members"}), (b:Schema {id: "schema:membership"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:notifications"}), (b:Schema {id: "schema:notification"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:phase_agent_profiles"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:phase_agent_profiles"}), (b:Schema {id: "schema:phase_agent_profile"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:phase_agent_profiles"}), (b:Model {id: "model:phase_agent_profile"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:planner"}), (b:Service {id: "service:planner_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:planner"}), (b:Schema {id: "schema:prompt_intake"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:planner_results"}), (b:Schema {id: "schema:planner_result"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:planner_results"}), (b:Model {id: "model:planner_result"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:project_templates"}), (b:Schema {id: "schema:project_template"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:projects"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:projects"}), (b:Schema {id: "schema:project"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:release_ops"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:release_ops"}), (b:Schema {id: "schema:release_ops"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:release_ops"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:release_ops"}), (b:Model {id: "model:release_ops"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:replay"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:replay"}), (b:Schema {id: "schema:replay"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:replay"}), (b:Model {id: "model:replay_snapshot"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:repos"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:repos"}), (b:Schema {id: "schema:repo"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:repos"}), (b:Model {id: "model:repo_connection"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:retry"}), (b:Service {id: "service:task_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:run_lifecycle"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:run_lifecycle"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:runs"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:runs"}), (b:Schema {id: "schema:run"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:runs"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:saved_views"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:saved_views"}), (b:Schema {id: "schema:saved_view"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:search_knowledge"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:search_knowledge"}), (b:Schema {id: "schema:search_knowledge"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:search_knowledge"}), (b:Model {id: "model:project_knowledge"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:search_knowledge"}), (b:Model {id: "model:search_knowledge"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:search_knowledge"}), (b:Model {id: "model:project_template"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:streaming"}), (b:Service {id: "service:stream_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:tasks"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:tasks"}), (b:Schema {id: "schema:task"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:trust"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:trust"}), (b:Schema {id: "schema:trust"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Route {id: "route:trust"}), (b:Model {id: "model:trust_score"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Route {id: "route:workspaces"}), (b:Service {id: "service:authz_service"}) MERGE (a)-[:CALLS]->(b);
MATCH (a:Route {id: "route:workspaces"}), (b:Schema {id: "schema:workspace"}) MERGE (a)-[:VALIDATES_WITH]->(b);
MATCH (a:Service {id: "service:activity_service"}), (b:Model {id: "model:activity"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:adaptive_orchestrator"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:adaptive_orchestrator"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:adaptive_orchestrator"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:adaptive_orchestrator"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:adaptive_retry_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:adaptive_retry_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:adaptive_retry_service"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:adr_service"}), (b:Model {id: "model:architecture"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:agent_service"}), (b:Model {id: "model:agent"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:api_key_service"}), (b:Model {id: "model:api_ecosystem"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:approval_enhanced_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:approval_enhanced_service"}), (b:Model {id: "model:membership"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:approval_enhanced_service"}), (b:Model {id: "model:approval_delegation"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:approval_service"}), (b:Service {id: "service:stream_service"}) MERGE (a)-[:DEPENDS_ON]->(b);
MATCH (a:Service {id: "service:approval_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:approval_service"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:architecture_approval_service"}), (b:Model {id: "model:architecture"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:architecture_approval_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:architecture_rule_service"}), (b:Model {id: "model:architecture"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:architecture_service"}), (b:Model {id: "model:architecture"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:artifact_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:artifact_version_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:audit_export_service"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:audit_log_service"}), (b:Model {id: "model:enterprise_governance"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:authz_service"}), (b:Model {id: "model:enterprise_governance"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:authz_service"}), (b:Model {id: "model:membership"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:background_scheduler"}), (b:Model {id: "model:workspace"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:background_scheduler"}), (b:Model {id: "model:analytics_metrics"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:chat_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:ci_pipeline_service"}), (b:Model {id: "model:github_integration"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:code_graph_service"}), (b:Model {id: "model:code_intelligence"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:code_ops_service"}), (b:Model {id: "model:code_ops"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:code_review_service"}), (b:Model {id: "model:github_integration"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:comment_service"}), (b:Model {id: "model:comment"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:compliance_report_service"}), (b:Model {id: "model:enterprise_governance"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:compliance_report_service"}), (b:Model {id: "model:membership"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:compliance_report_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:compliance_report_service"}), (b:Model {id: "model:project"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:composition_service"}), (b:Model {id: "model:phase_agent_profile"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:composition_service"}), (b:Model {id: "model:agent"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:connector_service"}), (b:Model {id: "model:connector"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:connector_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:connector_service"}), (b:Model {id: "model:project_connector_link"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:constitution_service"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:constitution_service"}), (b:Model {id: "model:project_constitution"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:constitution_suggestion_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:constitution_suggestion_service"}), (b:Model {id: "model:project_knowledge"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:constitution_suggestion_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:constitution_suggestion_service"}), (b:Model {id: "model:constitution_suggestion"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:convention_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:convention_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:convention_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:convention_service"}), (b:Model {id: "model:search_knowledge"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:cost_tracking_service"}), (b:Model {id: "model:cost_record"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:council_service"}), (b:Model {id: "model:council"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:credential_vault_service"}), (b:Service {id: "service:encryption_service"}) MERGE (a)-[:DEPENDS_ON]->(b);
MATCH (a:Service {id: "service:credential_vault_service"}), (b:Model {id: "model:credential_vault"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:credential_vault_service"}), (b:Model {id: "model:connector"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:dashboard_alert_service"}), (b:Model {id: "model:analytics_metrics"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:delivery_artifact_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:delivery_artifact_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:delivery_artifact_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:delivery_artifact_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:delivery_artifact_service"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:deployment_readiness_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:deployment_readiness_service"}), (b:Model {id: "model:release_ops"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:deployment_readiness_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:deployment_readiness_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:deployment_readiness_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:deployment_readiness_service"}), (b:Model {id: "model:execution_checkpoint"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:design_doc_service"}), (b:Model {id: "model:architecture"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:drift_detection_service"}), (b:Model {id: "model:architecture"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:embedding_service"}), (b:Model {id: "model:search_knowledge"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:environment_service"}), (b:Model {id: "model:release_ops"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:escalation_service"}), (b:Model {id: "model:escalation"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:event_service"}), (b:Service {id: "service:stream_service"}) MERGE (a)-[:DEPENDS_ON]->(b);
MATCH (a:Service {id: "service:event_service"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:execution_checkpoint_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:execution_checkpoint_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:execution_checkpoint_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:execution_checkpoint_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:execution_checkpoint_service"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:execution_checkpoint_service"}), (b:Model {id: "model:execution_checkpoint"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:execution_health_service"}), (b:Model {id: "model:cost_record"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:execution_health_service"}), (b:Model {id: "model:code_intelligence"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:execution_health_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:execution_health_service"}), (b:Model {id: "model:analytics_metrics"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:execution_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:execution_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:execution_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:execution_service"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:execution_service"}), (b:Model {id: "model:execution_checkpoint"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:flakiness_complexity_service"}), (b:Model {id: "model:code_intelligence"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:github_installation_service"}), (b:Service {id: "service:encryption_service"}) MERGE (a)-[:DEPENDS_ON]->(b);
MATCH (a:Service {id: "service:github_installation_service"}), (b:Model {id: "model:github_integration"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:governance_engine_service"}), (b:Model {id: "model:enterprise_governance"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:governance_engine_service"}), (b:Model {id: "model:governance_policy"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:governance_engine_service"}), (b:Model {id: "model:project"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:governance_service"}), (b:Model {id: "model:governance_policy"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:impact_analysis_service"}), (b:Model {id: "model:architecture"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:integration_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:integration_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:integration_service"}), (b:Model {id: "model:project"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:ip_allowlist_service"}), (b:Model {id: "model:enterprise_governance"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:issue_sync_service"}), (b:Model {id: "model:github_integration"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:knowledge_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:knowledge_service"}), (b:Model {id: "model:project_knowledge"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:knowledge_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:knowledge_service"}), (b:Model {id: "model:planner_result"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:membership_service"}), (b:Model {id: "model:membership"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:membership_service"}), (b:Model {id: "model:project"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:mention_service"}), (b:Model {id: "model:notification"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:mention_service"}), (b:Model {id: "model:user"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:merge_readiness_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:merge_readiness_service"}), (b:Model {id: "model:github_integration"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:merge_readiness_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:notification_delivery_service"}), (b:Model {id: "model:notification"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:notification_digest_service"}), (b:Model {id: "model:notification"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:notification_service"}), (b:Model {id: "model:notification"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:operational_timeline_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:operational_timeline_service"}), (b:Model {id: "model:release_ops"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:operational_timeline_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:operational_timeline_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:operational_timeline_service"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:operational_timeline_service"}), (b:Model {id: "model:execution_checkpoint"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:pattern_debt_service"}), (b:Model {id: "model:project_knowledge"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:pattern_debt_service"}), (b:Model {id: "model:code_intelligence"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:phase_agent_profile_service"}), (b:Model {id: "model:phase_agent_profile"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:phase_agent_profile_service"}), (b:Model {id: "model:agent"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:plan_artifact_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:plan_artifact_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:plan_artifact_service"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:plan_artifact_service"}), (b:Model {id: "model:project"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:planner_service"}), (b:Service {id: "service:code_graph_service"}) MERGE (a)-[:DEPENDS_ON]->(b);
MATCH (a:Service {id: "service:planner_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:planner_service"}), (b:Model {id: "model:project"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:planner_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:planner_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:planner_service"}), (b:Model {id: "model:planner_result"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:post_release_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:post_release_service"}), (b:Model {id: "model:release_ops"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:post_release_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:post_release_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:post_release_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:post_release_service"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:post_release_service"}), (b:Model {id: "model:execution_checkpoint"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:pr_service"}), (b:Model {id: "model:github_integration"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:project_overview_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:project_overview_service"}), (b:Model {id: "model:membership"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:project_overview_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:project_overview_service"}), (b:Model {id: "model:project"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:project_overview_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:project_service"}), (b:Service {id: "service:saved_view_service"}) MERGE (a)-[:DEPENDS_ON]->(b);
MATCH (a:Service {id: "service:project_service"}), (b:Model {id: "model:membership"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:project_service"}), (b:Model {id: "model:project"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:project_template_service"}), (b:Model {id: "model:project_template"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:recommendation_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:recommendation_service"}), (b:Model {id: "model:project_knowledge"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:recommendation_service"}), (b:Model {id: "model:search_knowledge"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:recommendation_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:recommendation_service"}), (b:Model {id: "model:project"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:recommendation_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:refactor_recommendation_service"}), (b:Model {id: "model:architecture"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:release_confidence_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:release_confidence_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:release_confidence_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:release_confidence_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:release_confidence_service"}), (b:Model {id: "model:execution_checkpoint"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:release_gate_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:release_gate_service"}), (b:Model {id: "model:release_ops"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:release_gate_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:release_gate_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:release_gate_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:release_gate_service"}), (b:Model {id: "model:execution_checkpoint"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:release_package_service"}), (b:Model {id: "model:release_ops"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:release_package_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:release_package_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:release_package_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:release_package_service"}), (b:Model {id: "model:execution_checkpoint"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:replay_service"}), (b:Model {id: "model:replay_snapshot"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:repo_service"}), (b:Model {id: "model:repo_connection"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:retention_policy_service"}), (b:Model {id: "model:enterprise_governance"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:retention_policy_service"}), (b:Model {id: "model:notification"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:retention_policy_service"}), (b:Model {id: "model:membership"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:retention_policy_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:retention_policy_service"}), (b:Model {id: "model:project"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:retention_policy_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:rollback_readiness_service"}), (b:Model {id: "model:release_ops"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:rollback_readiness_service"}), (b:Model {id: "model:execution_checkpoint"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_annotation_service"}), (b:Model {id: "model:run_annotation"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_comparison_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_comparison_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_comparison_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_lifecycle_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_lifecycle_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_lifecycle_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_lifecycle_service"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_lifecycle_service"}), (b:Model {id: "model:execution_checkpoint"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_memory_enrichment_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_memory_enrichment_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_memory_enrichment_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_memory_enrichment_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_memory_enrichment_service"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_memory_enrichment_service"}), (b:Model {id: "model:execution_checkpoint"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_memory_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_memory_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_memory_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_memory_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:run_memory_service"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:saved_view_service"}), (b:Model {id: "model:saved_view"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:search_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:search_service"}), (b:Model {id: "model:project_knowledge"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:search_service"}), (b:Model {id: "model:search_knowledge"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:search_service"}), (b:Model {id: "model:membership"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:search_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:search_service"}), (b:Model {id: "model:project"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:search_service"}), (b:Model {id: "model:run_annotation"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:search_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:search_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:search_service"}), (b:Model {id: "model:comment"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:slash_command_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:slash_command_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:spec_plan_approval_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:spec_plan_approval_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:spec_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:spec_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:spec_service"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:spec_service"}), (b:Model {id: "model:project"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:sso_configuration_service"}), (b:Model {id: "model:workspace"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:sso_configuration_service"}), (b:Model {id: "model:sso_configuration"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:structural_health_service"}), (b:Model {id: "model:architecture"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:task_assignment_service"}), (b:Service {id: "service:event_service"}) MERGE (a)-[:DEPENDS_ON]->(b);
MATCH (a:Service {id: "service:task_assignment_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:task_assignment_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:task_assignment_service"}), (b:Model {id: "model:execution_event"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:task_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:task_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:template_inheritance_service"}), (b:Model {id: "model:phase_agent_profile"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:template_inheritance_service"}), (b:Model {id: "model:agent"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:template_inheritance_service"}), (b:Model {id: "model:project"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:template_inheritance_service"}), (b:Model {id: "model:project_template"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:topology_mapper_service"}), (b:Model {id: "model:architecture"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:traceability_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:traceability_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:traceability_service"}), (b:Model {id: "model:artifact"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:traceability_service"}), (b:Model {id: "model:planner_result"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:traceability_service"}), (b:Model {id: "model:execution_checkpoint"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:trust_scoring_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:trust_scoring_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:trust_scoring_service"}), (b:Model {id: "model:trust_score"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:unified_activity_service"}), (b:Model {id: "model:activity"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:user_activity_service"}), (b:Model {id: "model:activity"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:user_activity_service"}), (b:Model {id: "model:membership"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:velocity_quality_service"}), (b:Model {id: "model:approval_request"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:velocity_quality_service"}), (b:Model {id: "model:analytics_metrics"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:velocity_quality_service"}), (b:Model {id: "model:run"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:velocity_quality_service"}), (b:Model {id: "model:task"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:velocity_quality_service"}), (b:Model {id: "model:cost_record"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:velocity_quality_service"}), (b:Model {id: "model:code_intelligence"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:webhook_connector_service"}), (b:Model {id: "model:api_ecosystem"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:webhook_service"}), (b:Model {id: "model:github_integration"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:workspace_service"}), (b:Model {id: "model:workspace"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Service {id: "service:workspace_service"}), (b:Model {id: "model:membership"}) MERGE (a)-[:PERSISTS]->(b);
MATCH (a:Page {id: "page:activity"}), (b:LibClient {id: "lib:activity"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:activity"}), (b:LibClient {id: "lib:activity"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:activity"}), (b:LibClient {id: "lib:activity"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:agents"}), (b:LibClient {id: "lib:agents"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:agents"}), (b:LibClient {id: "lib:agents"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:approvals"}), (b:LibClient {id: "lib:approvals"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:approvals"}), (b:LibClient {id: "lib:approvals"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:architecture"}), (b:LibClient {id: "lib:architecture"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:architecture"}), (b:LibClient {id: "lib:architecture"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:architecture"}), (b:LibClient {id: "lib:architecture"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:artifacts"}), (b:LibClient {id: "lib:artifacts"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:artifacts"}), (b:LibClient {id: "lib:artifacts"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:audit"}), (b:LibClient {id: "lib:audit"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:audit"}), (b:LibClient {id: "lib:audit"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:audit"}), (b:LibClient {id: "lib:audit"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:connectors"}), (b:LibClient {id: "lib:connectors"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:connectors"}), (b:LibClient {id: "lib:connectors"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:costs"}), (b:LibClient {id: "lib:costs"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:costs"}), (b:LibClient {id: "lib:costs"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:council"}), (b:LibClient {id: "lib:council"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:council"}), (b:LibClient {id: "lib:council"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:council"}), (b:LibClient {id: "lib:council"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:escalations"}), (b:LibClient {id: "lib:escalations"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:escalations"}), (b:LibClient {id: "lib:escalations"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:governance"}), (b:LibClient {id: "lib:governance"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:governance"}), (b:LibClient {id: "lib:governance"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:governance"}), (b:LibClient {id: "lib:governance"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:knowledge"}), (b:LibClient {id: "lib:knowledge"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:knowledge"}), (b:LibClient {id: "lib:knowledge"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:knowledge"}), (b:LibClient {id: "lib:knowledge"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:notifications"}), (b:LibClient {id: "lib:notifications"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:notifications"}), (b:LibClient {id: "lib:notifications"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:projects"}), (b:LibClient {id: "lib:projects"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:projects"}), (b:LibClient {id: "lib:projects"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:replay"}), (b:LibClient {id: "lib:replay"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:replay"}), (b:LibClient {id: "lib:replay"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:replay"}), (b:LibClient {id: "lib:replay"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:runs"}), (b:LibClient {id: "lib:runs"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:runs"}), (b:LibClient {id: "lib:runs"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:trust"}), (b:LibClient {id: "lib:trust"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:trust"}), (b:LibClient {id: "lib:trust"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:trust"}), (b:LibClient {id: "lib:trust"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:vault"}), (b:LibClient {id: "lib:vault"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:vault"}), (b:LibClient {id: "lib:vault"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:vault"}), (b:LibClient {id: "lib:vault"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:workspaces"}), (b:LibClient {id: "lib:workspaces"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:workspaces"}), (b:LibClient {id: "lib:workspaces"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:dashboard"}), (b:LibClient {id: "lib:projects"}) MERGE (a)-[:USES]->(b);
MATCH (a:Page {id: "page:dashboard"}), (b:LibClient {id: "lib:approvals"}) MERGE (a)-[:USES]->(b);
MATCH (a:LibClient {id: "lib:activity"}), (b:Route {id: "route:activity"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:agents"}), (b:Route {id: "route:agents"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:approvals"}), (b:Route {id: "route:approvals"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:architecture"}), (b:Route {id: "route:architecture"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:artifacts"}), (b:Route {id: "route:artifacts"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:audit"}), (b:Route {id: "route:audit"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:chat"}), (b:Route {id: "route:chat"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:connectors"}), (b:Route {id: "route:connectors"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:constitution-suggestions"}), (b:Route {id: "route:constitution_suggestions"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:constitution"}), (b:Route {id: "route:constitution"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:costs"}), (b:Route {id: "route:costs"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:council"}), (b:Route {id: "route:council"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:dashboards"}), (b:Route {id: "route:analytics"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:escalations"}), (b:Route {id: "route:escalation"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:events"}), (b:Route {id: "route:events"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:governance"}), (b:Route {id: "route:governance"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:governance"}), (b:Route {id: "route:enterprise_governance"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:knowledge"}), (b:Route {id: "route:knowledge"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:knowledge"}), (b:Route {id: "route:search_knowledge"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:notifications"}), (b:Route {id: "route:notifications"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:phase-profiles"}), (b:Route {id: "route:phase_agent_profiles"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:planner"}), (b:Route {id: "route:planner"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:planner"}), (b:Route {id: "route:planner_results"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:project-members"}), (b:Route {id: "route:members"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:projects"}), (b:Route {id: "route:projects"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:projects"}), (b:Route {id: "route:project_templates"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:release-ops"}), (b:Route {id: "route:release_ops"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:replay"}), (b:Route {id: "route:replay"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:runs"}), (b:Route {id: "route:runs"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:runs"}), (b:Route {id: "route:run_lifecycle"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:stream"}), (b:Route {id: "route:streaming"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:tasks"}), (b:Route {id: "route:tasks"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:templates"}), (b:Route {id: "route:project_templates"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:trust"}), (b:Route {id: "route:trust"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:vault"}), (b:Route {id: "route:credential_vault"}) MERGE (a)-[:HITS]->(b);
MATCH (a:LibClient {id: "lib:workspaces"}), (b:Route {id: "route:workspaces"}) MERGE (a)-[:HITS]->(b);
