import uuid

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.auth_stub import get_current_user_id
from app.db.session import get_db
from app.schemas.prompt_intake import PromptIntakeRequest, PromptIntakeResponse
from app.services.planner_service import plan_from_prompt

router = APIRouter()


@router.post("/planner/intake", response_model=PromptIntakeResponse, status_code=201)
async def prompt_intake(
    data: PromptIntakeRequest,
    db: AsyncSession = Depends(get_db),
    owner_id: uuid.UUID = Depends(get_current_user_id),
) -> PromptIntakeResponse:
    """Accept a natural-language prompt, create a project + run + planning tasks."""
    project, run, tasks, planner_result = await plan_from_prompt(
        db,
        prompt=data.prompt,
        owner_id=owner_id,
        project_name=data.project_name,
    )
    is_stub = (planner_result.overview or "").startswith("Stub planning result")
    message = (
        "Project planned with stub tasks — configure an LLM API key for real planning."
        if is_stub
        else f"Project planned successfully — {len(tasks)} tasks generated by AI planner."
    )
    return PromptIntakeResponse(
        project_id=project.id,
        run_id=run.id,
        tasks_created=len(tasks),
        message=message,
        created_at=project.created_at,
    )
